// frontend-development/framework-basics/react-sample/src/components/BeerVote.jsx
import './BeerVote.css';
import { useState } from "react";

function BeerVote() {
  const [count, setCount] = useState(0);

  return (
    <div className="beer-vote">
      <p>Votes: {count}</p>
      <button  className="beer-vote-button" onClick={() => setCount(count + 1)}>👍</button>
      <button  className="beer-vote-button" onClick={() => setCount(count - 1)}>👎</button>
    </div>
  );
}

export default BeerVote;

// frontend-development/framework-basics/angular-sample/src/app/components/beer-vote/beer-vote.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-beer-vote',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './beer-vote.component.html',
  styleUrl: './beer-vote.component.css'
})
export class BeerVoteComponent {
  public count = 0;

  public increase() {
    this.count++;
  }

  public decrease() {
    this.count--;
  }
}

<div class="beer-vote">
  <p>Votes: {{count}}</p>
  <button class="beer-vote-button" (click)="increase()">👍</button>
  <button class="beer-vote-button" (click)="decrease()">👎</button>
</div>
