// archive/frontend-development/framework-basics/react-sample/src/App.jsx
import { Outlet } from "react-router-dom";
import "./App.css";
import Navigation from "./components/Navigation";

function App() {
  return (
    <div className="app-container">
      <h1 className="title">Hello React!</h1>
      <div className="app-content-container">
        <Navigation />
        <div className="app-content">
          <Outlet />
        </div>
      </div>
    </div>
  );
}

export default App;

// frontend-development/framework-basics/angular-sample/src/app/app.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet } from '@angular/router';
import { NavigationComponent } from './components/navigation/navigation.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    CommonModule,
    RouterOutlet,
    NavigationComponent,
  ],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'angular-sample';
}

<div class="app-container">
  <h1 class="title">Hello Angular!</h1>
  <div class="app-content-container">
    <app-navigation></app-navigation>
    <div class="app-content">
      <router-outlet></router-outlet>
    </div>
  </div>
</div>
