// 04-frontend/02-angular/beer-app-angular/src/app/ui/beer-create-card/beer-create-card.component.ts
import { Component } from '@angular/core';
import { CardComponent } from '../cards/card/card.component';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-beer-create-card',
  standalone: true,
  imports: [CardComponent, RouterLink],
  templateUrl: './beer-create-card.component.html',
  styleUrl: './beer-create-card.component.css'
})
export class BeerCreateCardComponent {

}

<a routerLink="/create">
  <app-card [card]="{ title: 'Create a new beer', subtitle: '' }">
    <div class="content" ngProjectAs="card-content">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        width="100"
        height="100"
      >
        <line x1="4" y1="12" x2="20" y2="12" stroke="black" strokeWidth="2" />
        <line x1="12" y1="4" x2="12" y2="20" stroke="black" strokeWidth="2" />
      </svg>
    </div>
    <div class="footer" ngProjectAs="card-footer">
      <p>Add a new beer to the list</p>
    </div>
  </app-card>
</a>

// 04-frontend/01-nextjs/beer-app-nextjs/src/app/ui/beer-create-card.tsx
import Link from "next/link";
import styles from "./beer-card.module.css";
import { Card } from "./cards/card";

export function BeerCreateCard() {
  const CreateIcon = () => (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      width="100"
      height="100"
    >
      <line x1="4" y1="12" x2="20" y2="12" stroke="black" strokeWidth="2" />
      <line x1="12" y1="4" x2="12" y2="20" stroke="black" strokeWidth="2" />
    </svg>
  );

  return (
    <Link href="/create">
      <Card
        card={{
          title: "Create a new beer",
          subtitle: "",
        }}
      >
        <div className={styles.content}>
          <CreateIcon></CreateIcon>
        </div>
        <div className={styles.footer}>
          <p>Add a new beer to the list</p>
        </div>
      </Card>
    </Link>
  );
}
