// frontend-development/framework-basics/react-sample/src/components/BeerCreate.jsx
/* eslint-disable react/prop-types */
import "./BeerCreate.css";
import { useState } from "react";

function BeerCreate({ addBeerItem }) {
  const [beer, setBeer] = useState({
    name: "",
    taste: "",
  });

  function handleNameChange(e) {
    setBeer({ ...beer, name: e.target.value });
  }

  function handleTasteChange(e) {
    setBeer({ ...beer, taste: e.target.value });
  }

  const handleCreate = async () => {
    const request = await fetch("http://localhost:8080/api/v1/beers", {
      method: "POST",
      body: JSON.stringify(beer),
      headers: { "Content-type": "application/json; charset=UTF-8" },
    });

    if (request.ok) {
      setBeer({ name: "", taste: "" });
      const response = await request.json();
      addBeerItem({
        name: response.createdItem.name,
        taste: response.createdItem.taste,
        id: response.createdItem.id,
      });
    }
  };

  return (
    <div>
      <h2>Create new Beer</h2>
      <div className="beer-create-inputs">
      <label>
            Beer Name:
            <input type="text" value={beer.name} onChange={handleNameChange} />
          </label>
          <label>
            Beer Taste:
            <input
              type="text"
              value={beer.taste}
              onChange={handleTasteChange}
            />
          </label>
          <button onClick={handleCreate}>Create</button>
      </div>
    </div>
  );
}

export default BeerCreate;

// frontend-development/framework-basics/vue-sample/src/components/BeerCreate.vue
<script setup>
import { reactive } from "vue";

const emit = defineEmits(["createBeer"]);

const beer = reactive({
  name: "",
  taste: "",
});

async function handleCreate() {
  const request = await fetch("http://localhost:8080/api/v1/beers", {
    method: "POST",
    headers: { "Content-type": "application/json; charset=UTF-8" },
    body: JSON.stringify({
      name: beer.name,
      taste: beer.taste,
    }),
  });

  if (request.ok) {
    beer.name = "";
    beer.taste = "";
    const response = await request.json();
    emit("createBeer", {
      name: response.createdItem.name,
      taste: response.createdItem.taste,
    });
  }
}
</script>

<template>
  <div>
    <h2>Create new Beer</h2>
    <div class="beer-create-inputs">
      <label>
        Beer Name:
        <input type="text" v-model="beer.name" />
      </label>
      <label>
        Beer Taste:
        <input type="text" v-model="beer.taste" />
      </label>
      <button @click="handleCreate">Create</button>
    </div>
  </div>
</template>

<style scoped>
.beer-create-inputs {
  display: flex;
  flex-direction: column;
  gap: 24px;
}
</style>
