// 04-frontend/01-react/app/components/playground/playground.tsx
import { Card } from "../card/card";
import { CardContent } from "../card/card-content";
import { CardFooter } from "../card/card-footer";
import { CardHeader } from "../card/card-header";

export default function Playground() {
  return (
    <Card>
      <CardHeader title="Beer" subTitle="Wasseralfinger" />
      <CardContent>
        <p>This is projected into the card as the content slot.</p>
      </CardContent>
      <CardFooter>
        <button>Drink</button>
        <button>Vote</button>
      </CardFooter>
    </Card>
  );
}

// 04-frontend/02-angular/src/app/components/playground/playground.ts
import { Component } from '@angular/core';
import { Card } from '../card/card/card';
import { CardHeader } from '../card/card-header/card-header';
import { CardContent } from '../card/card-content/card-content';
import { CardFooter } from '../card/card-footer/card-footer';

@Component({
  selector: 'app-playground',
  imports: [Card, CardHeader, CardContent, CardFooter],
  templateUrl: './playground.html',
  styleUrl: './playground.css',
})
export class Playground {}
