// 04-frontend/01-nextjs/beer-app-nextjs/src/app/ui/beer-header.tsx
"use client";

import { useState } from "react";
import styles from "./beer-header.module.css";
import Link from "next/link";

export default function BeerHeader() {
  const [isHovered, setIsHovered] = useState(false);

  return (
    <div className={styles.header}>
      <div className={styles.title}>
        <h1>Beer App</h1>
        <h1
          onMouseEnter={() => setIsHovered(true)}
          onMouseLeave={() => setIsHovered(false)}
          className={isHovered ? styles.shake : ""}
        >
          🍻
          {isHovered && <span className={styles.prost}>Prost!</span>}
        </h1>
      </div>
      <nav className={styles.navigation}>
        <Link href="/">🍺 Home</Link>
        <a
          href="https://www.bierbewusstgeniessen.de/drink-responsibly/"
          target="_blank"
        >
          ⚠️ Drink Responsible
        </a>
      </nav>
    </div>
  );
}

// 04-frontend/02-angular/beer-app-angular/src/app/ui/beer-header/beer-header.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-beer-header',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './beer-header.component.html',
  styleUrl: './beer-header.component.css'
})
export class BeerHeaderComponent {
  public isHovered: boolean = false;
}

<div class="header">
  <div class="title">
    <h1>Beer App</h1>
    <h1
      (mouseenter)="isHovered = true"
      (mouseleave)="isHovered = false"
      [class]="isHovered ? 'shake' : ''"
    >
      🍻
      @if (isHovered) {
        <span class="prost">Prost!</span>
      }
    </h1>
  </div>
  <nav class="navigation">
    <a routerLink="/">🍺 Home</a>
    <a
      href="https://www.bierbewusstgeniessen.de/drink-responsibly/"
      target="_blank"
    >
      ⚠️ Drink Responsible
    </a>
  </nav>
</div>
