// archive/frontend-development/framework-basics/react-sample/src/components/details/BeerDetail.jsx
import { useLoaderData } from "react-router-dom";
import { fetchBeer } from "../../api/api";
import Beer2 from "../beer/Beer2";

export async function beerDetailLoader({ params }) {
  const beer = await fetchBeer(params.beerId);
  return { beer };
}

function BeerDetail() {
  const { beer } = useLoaderData();

  return (
    <>
      <Beer2 beer={beer}></Beer2>
    </>
  );
}

export default BeerDetail;

// archive/frontend-development/framework-basics/vue-sample/src/components/details/BeerDetail.vue
<script setup>
import { onMounted } from "vue";
import { useRoute } from "vue-router";
import { ref } from "vue";
import { fetchBeer } from "../../api/api";
import Beer2 from "../beer/Beer2.vue";

const route = useRoute();
const beerId = ref(route.params.beerId);
const beer = ref(null);

onMounted(async () => {
  beer.value = await fetchBeer(beerId.value);
});
</script>

<template>
  <Beer2 v-if="beer" :beer="beer"></Beer2>
</template>

<style scoped></style>
