// 04-frontend/01-nextjs/beer-app-nextjs/src/app/ui/beer-create.tsx
"use client";

import { useFormStatus } from "react-dom";
import styles from "./beer-create.module.css";
import { useActionState } from "react";
import { createBeer } from "../create/actions";

const initialState = {
  name: "",
  taste: "",
  brand: "",
};

function SubmitButton() {
  const { pending } = useFormStatus();

  return (
    <button type="submit" aria-disabled={pending}>
      Create
    </button>
  );
}

export default function BeerCreate() {
  const [state, formAction] = useActionState(createBeer, initialState);

  return (
    <div className={styles.layout}>
      <form action={formAction}>
        <h1>New Beer 🍺</h1>
        <label htmlFor="name">Name</label>
        <input type="text" id="name" name="name" required />
        <label htmlFor="taste">Taste</label>
        <input type="text" id="taste" name="taste" required />
        <label htmlFor="brand">Brand</label>
        <input type="text" id="brand" name="brand" required />
        <SubmitButton />
      </form>
    </div>
  );
}

// 04-frontend/02-angular/beer-app-angular/src/app/ui/beer-create/beer-create.component.ts
import { Component } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { BeerApiService } from '../../shared/beer-api.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-beer-create',
  standalone: true,
  imports: [ReactiveFormsModule],
  templateUrl: './beer-create.component.html',
  styleUrl: './beer-create.component.css'
})
export class BeerCreateComponent {
  constructor(private beerApiService: BeerApiService, private router: Router) {}

  public createBeerForm = new FormGroup({
    name: new FormControl(null, [Validators.required]),
    taste: new FormControl(null, [Validators.required]),
    brand: new FormControl(null, [Validators.required])
  });

  public handleFormSubmit() {
    this.beerApiService.createBeer(this.createBeerForm).subscribe(() => {
      this.router.navigate(['/']);
    });
  }
}

<div class="layout">
  <form [formGroup]="createBeerForm" (ngSubmit)="handleFormSubmit()">
    <h1>New Beer 🍺</h1>
    <label for="name">Name</label>
    <input type="text" formControlName="name" id="name" required />
    <label for="taste">Taste</label>
    <input type="text" formControlName="taste" id="taste" required />
    <label for="brand">Brand</label>
    <input type="text" formControlName="brand" id="brand" required />
    <button type="submit" [disabled]="createBeerForm.invalid">Create</button>
  </form>
</div>
