// 04-frontend/01-react/app/components/counter/counter.tsx
import { useState } from "react";
import IncrementButton from "../counter-button/counter-button";

export default function Counter() {
  const [count, setCount] = useState(0);

  const handleIncrement = () => {
    setCount((c) => c + 1);
  };

  const handleReset = () => {
    setCount(0);
  };

  return (
    <>
      <h1>Counter: {count}</h1>
      <IncrementButton increment={handleIncrement}></IncrementButton>
      <button onClick={handleReset}>Reset</button>
    </>
  );
}

// 04-frontend/02-angular/src/app/components/counter/counter.ts
import { Component, signal } from '@angular/core';
import { IncrementButton } from '../increment-button/increment-button';

@Component({
  selector: 'app-counter',
  imports: [IncrementButton],
  templateUrl: './counter.html',
  styleUrl: './counter.css',
})
export class Counter {
  count = signal(0);

  handleIncrement() {
    this.count.set(this.count() + 1);
  }

  handleReset() {
    this.count.set(0);
  }
}
