// 04-frontend/01-nextjs/beer-app-nextjs/src/app/ui/beer-card.tsx
"use client";

import { useState } from "react";
import styles from "./beer-card.module.css";
import BeerMug from "./beer-mug";
import { Card } from "./cards/card";
import { drinkBeer, rateBeer } from "../lib/beer-api";
import { BeerRatingSlider } from "./beer-rating-slider";

export function BeerCard({ providedBeer }) {
  const [beer, setBeer] = useState(providedBeer);

  const handleDrink = async () => {
    try {
      const apiResponse = await drinkBeer(beer);
      setBeer(() => ({ ...apiResponse.beer }));
    } catch (error) {
      console.error("Error drinking beer:", error);
    }
  };

  const handleRatingSelect = async (newRating) => {
    try {
      const apiResponse = await rateBeer(beer, newRating);
      setBeer(() => ({ ...apiResponse.beer }));
    } catch (error) {
      console.error("Error drinking beer:", error);
    }
  };

  return (
    <Card card={{ title: beer.name, subtitle: beer.brand }}>
      <div className={styles.content}>
        <BeerMug rating={beer.rating} onClick={handleDrink}></BeerMug>
      </div>
      <div className={styles.footer}>
        <h4>{beer.amount}</h4>
        <BeerRatingSlider
          currentRating={beer.rating}
          onRatingSelect={handleRatingSelect}
        ></BeerRatingSlider>
      </div>
    </Card>
  );
}

// 04-frontend/02-angular/beer-app-angular/src/app/ui/beer-card/beer-card.component.ts
import { Component, Input } from '@angular/core';
import { CardComponent } from '../cards/card/card.component';
import { BeerMugComponent } from '../beer-mug/beer-mug.component';
import { BeerRatingSliderComponent } from '../beer-rating-slider/beer-rating-slider.component';
import { BeerApiService } from '../../shared/beer-api.service';

@Component({
  selector: 'app-beer-card',
  standalone: true,
  imports: [CardComponent, BeerMugComponent, BeerRatingSliderComponent],
  templateUrl: './beer-card.component.html',
  styleUrl: './beer-card.component.css',
})
export class BeerCardComponent {
  @Input({ required: true }) beer!: any;

  constructor(private beerApiService: BeerApiService) {}

  public handleDrink() {
    this.beerApiService.drinkBeer(this.beer).subscribe((response) => {
      this.beer = response.beer;
    });
  }

  public handleRatingSelect(newRating: number) {
    this.beerApiService.rateBeer(this.beer, newRating).subscribe((response) => {
      this.beer = response.beer;
    });
  }
}

<app-card [card]="{ title: beer.name, subtitle: beer.brand }">
  <div class="content" ngProjectAs="card-content">
    <app-beer-mug
      [rating]="beer.rating"
      (clickEvent)="handleDrink()"
    ></app-beer-mug>
  </div>
  <div class="footer" ngProjectAs="card-footer">
    <app-beer-rating-slider
      [currentRating]="beer.rating"
      (ratingSelect)="handleRatingSelect($event)"
    ></app-beer-rating-slider>
    <h4>{{ beer.amount }}</h4>
  </div>
</app-card>
