// frontend-development/framework-basics/vue-sample/src/components/lists/BeerList3.vue
<script setup>
import Beer2 from "../beer/Beer2.vue";
import BeerVote from "../BeerVote.vue";
import BeerCreate from "../BeerCreate.vue";
import { ref } from "vue";

const isLoading = ref(true);
const beers = ref(null);

fetch("http://localhost:8080/api/v1/beers").then((response) => {
  return response.json();
}).then((data) => {
  beers.value = data.items;
  isLoading.value = false;
});
</script>

<template>
  <div v-if="isLoading">Loading...</div>
  <div v-else>
    <h2>Beer List</h2>
    <BeerCreate @createBeer="beers.push($event)"></BeerCreate>
    <div class="beer-list">
      <Beer2 v-for="(beer, index) in beers" :key="index" :beer="beer">
        <BeerVote></BeerVote>
      </Beer2>
    </div>
  </div>
</template>

<style scoped>
.beer-list {
  padding-top: 8px;
  display: flex;
  flex-direction: column;
  gap: 4px;
}
</style>

// frontend-development/framework-basics/react-sample/src/components/lists/BeerList3.jsx
import "./BeerList.css";
import Beer2 from "../beer/Beer2";
import BeerVote from "../BeerVote";
import { useEffect, useState } from "react";
import BeerCreate from "../BeerCreate";

function BeerList3() {
  const [beers, setBeers] = useState([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const dataFetch = async () => {
      const data = await (
        await fetch("http://localhost:8080/api/v1/beers")
      ).json();

      setBeers(data.items);
      setIsLoading(false);
    };

    dataFetch();
  }, []);

  const addBeerItem = (newBeer) => {
    setBeers([...beers, newBeer]);
  }

  if (isLoading) {
    return "Loading...";
  } else {
    return (
      <div>
        <h2>Beer List</h2>
        <BeerCreate addBeerItem={addBeerItem}></BeerCreate>
        <div className="beer-list">
          {beers.map((beer, index) => {
            return (
              <Beer2 key={index} beer={beer}>
                <BeerVote></BeerVote>
              </Beer2>
            );
          })}
        </div>
      </div>
    );
  }
}

export default BeerList3;
