// archive/frontend-development/framework-basics/angular-sample/src/app/components/lists/beer-list/beer-list.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Beer2Component } from '../../beer2/beer2.component';

@Component({
  selector: 'app-beer-list',
  standalone: true,
  imports: [CommonModule, Beer2Component],
  templateUrl: './beer-list.component.html',
  styleUrl: './beer-list.component.css'
})
export class BeerListComponent {
  public beers = [
    { name: 'Ulmer Goldochsen Kellerbier', id: 1, taste: 'good' },
    { name: 'Wasseralfinger', id: 2, taste: 'bad' },
    { name: 'Nattheimer Spezial', id: 3, taste: 'okay' },
  ]
}

// frontend-development/framework-basics/react-sample/src/components/lists/BeerList.jsx
import './BeerList.css';
import Beer from "../beer/Beer";

function BeerList() {
  const beers = [
    { name: 'Ulmer Goldochsen Kellerbier', id: 1, taste: 'good' },
    { name: 'Wasseralfinger', id: 2, taste: 'bad' },
    { name: 'Nattheimer Spezial', id: 3, taste: 'okay' },
  ]

  const listItems = beers.map((beer, index) => {
    return <Beer key={index}></Beer>
  })

  return (
    <div>
      <h2>Beer List</h2>
      <div className='beer-list'>{listItems}</div>
    </div>
  );
}

export default BeerList;
