// frontend-development/framework-basics/angular-sample/src/app/components/lists/beer-list2/beer-list2.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Beer2Component } from '../../beer2/beer2.component';
import { BeerVoteComponent } from '../../beer-vote/beer-vote.component';

@Component({
  selector: 'app-beer-list2',
  standalone: true,
  imports: [CommonModule, Beer2Component, BeerVoteComponent],
  templateUrl: './beer-list2.component.html',
  styleUrl: './beer-list2.component.css'
})
export class BeerList2Component {
  public beers = [
    { name: 'Ulmer Goldochsen Kellerbier', id: 1, taste: 'good' },
    { name: 'Wasseralfinger', id: 2, taste: 'bad' },
    { name: 'Nattheimer Spezial', id: 3, taste: 'okay' },
  ]
}

<div>
  <h2>Beer List</h2>
  <div class="beer-list">
    <app-beer2 *ngFor="let beer of beers" [beer]="beer">
      <app-beer-vote></app-beer-vote>
    </app-beer2>
  </div>
</div>

// frontend-development/framework-basics/react-sample/src/components/lists/BeerList2.jsx
import "./BeerList.css";
import Beer2 from "../beer/Beer2";
import BeerVote from "../BeerVote";

function BeerList2() {
  const beers = [
    { name: "Ulmer Goldochsen Kellerbier", id: 1, taste: "good" },
    { name: "Wasseralfinger", id: 2, taste: "bad" },
    { name: "Nattheimer Spezial", id: 3, taste: "okay" },
  ];

  const listItems = beers.map((beer) => {
    return (
      <Beer2 key={beer.id} beer={beer}>
        <BeerVote></BeerVote>
      </Beer2>
    );
  });

  return (
    <div>
      <h2>Beer List</h2>
      <div className="beer-list">{listItems}</div>
    </div>
  );
}

export default BeerList2;
