// 04-frontend/01-nextjs/beer-app-nextjs/src/app/ui/beer-footer.tsx
"use client";

import styles from "./beer-footer.module.css";

export default function BeerFooter() {
  return (
    <div className={styles.footer}>
      <div>
        <p>
          Diese Webseite dient nur für Unterhaltunszwecke und wurde im Rahmen
          der Web Programmierung Vorlesung 2024 entwickelt
        </p>
        <p>Made with ❤️ by Jens Reiner</p>
      </div>
      <div className={styles.links}>
        <a
          href="https://www.bundesdrogenbeauftragter.de/service/beratungsangebote/"
          target="_blank"
        >
          🔗 Beratungsangebote
        </a>
        <a
          href="https://www.dhs.de/service/suchthilfeverzeichnis"
          target="_blank"
        >
          🔗 Deutsche Hauptstelle für Suchtfragen
        </a>
      </div>
    </div>
  );
}

// 04-frontend/02-angular/beer-app-angular/src/app/ui/beer-footer/beer-footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-beer-footer',
  standalone: true,
  imports: [],
  templateUrl: './beer-footer.component.html',
  styleUrl: './beer-footer.component.css'
})
export class BeerFooterComponent {}

<div class="footer">
  <div>
    <p>
      Diese Webseite dient nur für Unterhaltunszwecke und wurde im Rahmen
      der Web Programmierung Vorlesung 2024 entwickelt
    </p>
    <p>Made with ❤️ by Jens Reiner</p>
  </div>
  <div class="links">
    <a
      href="https://www.bundesdrogenbeauftragter.de/service/beratungsangebote/"
      target="_blank"
    >
      🔗 Beratungsangebote
    </a>
    <a
      href="https://www.dhs.de/service/suchthilfeverzeichnis"
      target="_blank"
    >
      🔗 Deutsche Hauptstelle für Suchtfragen
    </a>
  </div>
</div>
