// frontend-development/framework-basics/angular-sample/src/app/components/beer2/beer2.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { faBeerMugEmpty } from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'app-beer2',
  standalone: true,
  imports: [CommonModule, FontAwesomeModule],
  templateUrl: './beer2.component.html',
  styleUrl: './beer2.component.css',
})
export class Beer2Component {
  @Input() beer!: { name: string; taste: string };

  faBeerBugEmpty = faBeerMugEmpty;
}

<div class="beer-card">
  <div class="beer-card-header">
    <fa-icon [icon]="faBeerBugEmpty"></fa-icon>
    <h3>{{beer.name}}</h3>
  </div>
  <div class="beer-card-body">
    <span>Taste: {{beer.taste}}</span>
    <ng-content></ng-content>
  </div>
</div>

// archive/frontend-development/framework-basics/react-sample/src/components/beer/Beer2.jsx
/* eslint-disable react/prop-types */
import './Beer.css'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

function Beer2({beer, children}) {
  return (
    <div className='beer-card'>
      <div className='beer-card-header'>
        <FontAwesomeIcon icon="fa-solid fa-beer-mug-empty" />
        <h3>{beer.name}</h3>
      </div>
      <div className='beer-card-body'>
        <span>Taste: {beer.taste}</span>
        {children}
      </div>
    </div>
  );
}

export default Beer2;
