// archive/frontend-development/framework-basics/vue-sample/src/App.vue
<script setup>
import Navigation from "./components/Navigation.vue";
</script>

<template>
  <div class="app-container">
    <h1 class="title">Hello Vue!</h1>
    <div class="app-content-container">
      <Navigation></Navigation>
      <div class="app-content">
        <router-view></router-view>
      </div>
    </div>
  </div>
</template>

<style scoped>
.title {
  font-size: 1.5em;
  text-align: center;
  color: palevioletred;
}

.app-container {
  display: flex;
  flex-direction: column;
}

.app-content-container {
  display: flex;
  flex-direction: column;
}

.app-content {
  flex-grow: 1;
}
</style>

// archive/frontend-development/framework-basics/react-sample/src/App.jsx
import { Outlet } from "react-router-dom";
import "./App.css";
import Navigation from "./components/Navigation";

function App() {
  return (
    <div className="app-container">
      <h1 className="title">Hello React!</h1>
      <div className="app-content-container">
        <Navigation />
        <div className="app-content">
          <Outlet />
        </div>
      </div>
    </div>
  );
}

export default App;
