// frontend-development/framework-basics/react-sample/src/components/lists/BeerList.jsx
import './BeerList.css';
import Beer from "../beer/Beer";

function BeerList() {
  const beers = [
    { name: 'Ulmer Goldochsen Kellerbier', id: 1, taste: 'good' },
    { name: 'Wasseralfinger', id: 2, taste: 'bad' },
    { name: 'Nattheimer Spezial', id: 3, taste: 'okay' },
  ]

  const listItems = beers.map((beer, index) => {
    return <Beer key={index}></Beer>
  })

  return (
    <div>
      <h2>Beer List</h2>
      <div className='beer-list'>{listItems}</div>
    </div>
  );
}

export default BeerList;

// archive/frontend-development/framework-basics/vue-sample/src/components/lists/BeerList.vue
<script setup>
import Beer from "../beer/Beer.vue";

const beers = [
  { name: "Ulmer Goldochsen Kellerbier", id: 1, taste: "good" },
  { name: "Wasseralfinger", id: 2, taste: "bad" },
  { name: "Nattheimer Spezial", id: 3, taste: "okay" },
];
</script>

<template>
  <div>
    <h2>Beer List</h2>
    <div class="beer-list">
      <Beer v-for="({beer}, index ) in beers" :key="index"></Beer>
    </div>
  </div>
</template>

<style>
.beer-list {
  padding-top: 8px;
  display: flex;
  flex-direction: column;
  gap: 4px;
}
</style>
